### ISSUE TITLE
ERROR: Kaldi's compute-wer was not found in your PATH!

### ISSUE THREAD

**Issue by RParedesPalacios** [jpuigcerver/Laia#13]
I have had several problems dealing with Laia.

First of all the problem of 
[2017-01-14 17:18:53 FATAL] /home/rparedes/torch/install/share/lua/5.1/cudnn/RNN.lua:252: dropout supported only in cudnn v5.1 and above

I have 5.05 but rnn_dropout is set to zero. I have modified the lea files to forced it to be zero. Finally i have had to modify RNN.lua an set there self.dropout=0 in order to pass the assert. 

After that i can run the run.sh:

Creating transcripts...  	Done.
Creating symbols table...  	Done.
Preprocessing images...  	Done.
ERROR: Kaldi's compute-wer was not found in your PATH!

and i get this error. Perhaps it is related to my modification and any model is created etc... i do not know, the run.sh doesn't pass the  th ../../laia-create-model step.

Any idea?

Meanwhile I wil update the cudann to the 5.1

**Comment by jpuigcerver** [comment]
Hi,

Regarding the first error, you should go to https://github.com/soumith/cudnn.torch since it is an error in their code.

In order to run the experiments, we assume that you have this tool installed (maybe we should have stated this explicitly in the README). compute-wer is a tool included in the Kaldi ASR toolkit: https://github.com/kaldi-asr/kaldi

 If you don't want to install Kaldi, you can just comment that line and/or adapt it to use your own tool to compute the CER/WER (e.g. tasas).
